# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
